/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Gst } from "./Gst";
import { GstCountArgs } from "./GstCountArgs";
import { GstFindManyArgs } from "./GstFindManyArgs";
import { GstFindUniqueArgs } from "./GstFindUniqueArgs";
import { CreateGstArgs } from "./CreateGstArgs";
import { UpdateGstArgs } from "./UpdateGstArgs";
import { DeleteGstArgs } from "./DeleteGstArgs";
import { GstService } from "../gst.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Gst)
export class GstResolverBase {
  constructor(
    protected readonly service: GstService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Gst",
    action: "read",
    possession: "any",
  })
  async _gstsMeta(
    @graphql.Args() args: GstCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Gst])
  @nestAccessControl.UseRoles({
    resource: "Gst",
    action: "read",
    possession: "any",
  })
  async gsts(@graphql.Args() args: GstFindManyArgs): Promise<Gst[]> {
    return this.service.gsts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Gst, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Gst",
    action: "read",
    possession: "own",
  })
  async gst(@graphql.Args() args: GstFindUniqueArgs): Promise<Gst | null> {
    const result = await this.service.gst(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gst)
  @nestAccessControl.UseRoles({
    resource: "Gst",
    action: "create",
    possession: "any",
  })
  async createGst(@graphql.Args() args: CreateGstArgs): Promise<Gst> {
    return await this.service.createGst({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gst)
  @nestAccessControl.UseRoles({
    resource: "Gst",
    action: "update",
    possession: "any",
  })
  async updateGst(@graphql.Args() args: UpdateGstArgs): Promise<Gst | null> {
    try {
      return await this.service.updateGst({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Gst)
  @nestAccessControl.UseRoles({
    resource: "Gst",
    action: "delete",
    possession: "any",
  })
  async deleteGst(@graphql.Args() args: DeleteGstArgs): Promise<Gst | null> {
    try {
      return await this.service.deleteGst(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
